image: node:8

cache:
  paths:
  - node_modules/

before_script:
  - npm install
  - mkdir -p /builds/karaokemugen/karaokemugen-app/app/data
  - mkdir -p /builds/karaokemugen/karaokemugen-app/app/db
  - cp -R samples/* /builds/karaokemugen/karaokemugen-app/app/data/ 

stages: 
  - test
  - deploy

test:
  stage: test
  script: 
    - bash test/run.sh

deploy:
  stage: deploy
  script: "echo lol2"
  only: 
    - master

