image: axelterizaki/karaokemugen-ci:node-12

cache:
  key: km-app-${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/
  - bin/
  - react_systempanel/node_modules/
  - dist/
  - react_systempanel/build/

stages:
  - test
  - build
  - package
  - deploy

test:
  stage: test
  retry:
    max: 2
  interruptible: true
  services:
    - postgres:10.6
  variables:
    POSTGRES_USER: karaokemugen_app
    POSTGRES_PASSWORD: musubi
  script:
    - yarn install --check-files --force
    - touch mpv
    - cp -f config.CICD.yml config.yml
    - mkdir -p /builds/karaokemugen/karaokemugen-app/app/data
    - cp -R samples/* /builds/karaokemugen/karaokemugen-app/app/data/
    - cp -f database.CICD.json database.json
    - export LANG=en_US
    - node --version
    - node util/extUnaccent.js
    - yarn start --debug --test &disown
    - bash test/run.sh
  only:
    - master
    - next
    - tags

build:
  stage: build
  interruptible: true
  artifacts:
    expire_in: 1 days
    name: km-app-build-${CI_COMMIT_REF_SLUG}
    paths:
    - react_systempanel/build/
    - dist/
  script:
    - npm install -g modclean parcel-bundler
    - yarn build
    - yarn buildReact
    - yarn install --production
    - cd node_modules
    - find -name *.node -delete
    - modclean -r
  only:
    - master
    - next
    - tags

pkg_win:
  stage: package
  interruptible: true
  artifacts:
    expire_in: 1 day
    name: km-app-pkgwin-${CI_COMMIT_REF_SLUG}
    paths:
    - bin/
  dependencies:
    - build
  script:
    - mkdir -p bin
    - npm install -g pkg@4.3.8
    - pkg . -d --targets node10-win-x64 --out-path bin
  only:
    - master
    - next
    - tags

pkg_win32:
  stage: package
  interruptible: true
  artifacts:
    expire_in: 1 day
    name: km-app-pkgwin32-${CI_COMMIT_REF_SLUG}
    paths:
    - bin/
  dependencies:
    - build
  script:
    - mkdir -p bin
    - npm install -g pkg@4.3.8
    - pkg . -d --targets node10-win-x86 -o bin/karaokemugen-app32.exe
  only:
    - master
    - next
    - tags

pkg_osx:
  stage: package
  interruptible: true
  artifacts:
    expire_in: 1 day
    name: km-app-pkgosx-${CI_COMMIT_REF_SLUG}
    paths:
    - bin/
  dependencies:
    - build
  script:
    - mkdir -p bin
    - npm install -g pkg@4.3.8
    - pkg . -d --targets node10-macos-x64 --out-path bin
  only:
    - master
    - next
    - tags

deploy_win:
  stage: deploy
  interruptible: true
  dependencies:
    - pkg_win
  cache: {}
  script:
    - mkdir build_win
    - cd build_win
    - wget -qO- http://mugen.karaokes.moe/downloads/dist_win.tar.gz | tar xvz
    - mkdir -p app/jingles
    - cd app/jingles
    - wget -qO- https://lab.shelter.moe/karaokemugen/jingles/repository/master/archive.tar | tar xv
    - mv -f jingles-master*/* .
    - rm -Rf jingles-master*
    - cd ../..
    - cp -f ../bin/karaokemugen-app.exe KaraokeMugen.exe
    - cp -f ../config.sample.yml .
    - cp -Rf ../samples .
    - zip -r KaraokeMugen-$CI_COMMIT_REF_NAME-win64.zip *
    - cd ..
    - lftp -c "set cmd:fail-exit yes; set ftp:ssl-allow no; open -u $USERNAME,$PASSWORD $HOST; cd site/downloads; put build_win/KaraokeMugen-$CI_COMMIT_REF_NAME-win64.zip"
  only:
    - master
    - next
    - tags

deploy_win32:
  stage: deploy
  interruptible: true
  dependencies:
    - pkg_win32
  cache: {}
  script:
    - mkdir build_win32
    - cd build_win32
    - wget -qO- http://mugen.karaokes.moe/downloads/dist_win32.tar.gz | tar xvz
    - mkdir -p app/jingles
    - cd app/jingles
    - wget -qO- https://lab.shelter.moe/karaokemugen/jingles/repository/master/archive.tar | tar xv
    - mv -f jingles-master*/* .
    - rm -Rf jingles-master*
    - cd ../..
    - cp -f ../bin/karaokemugen-app32.exe KaraokeMugen.exe
    - cp -f ../config.sample.yml .
    - cp -Rf ../samples .
    - zip -r KaraokeMugen-$CI_COMMIT_REF_NAME-win32.zip *
    - cd ..
    - lftp -c "set cmd:fail-exit yes; set ftp:ssl-allow no; open -u $USERNAME,$PASSWORD $HOST; cd site/downloads; put build_win32/KaraokeMugen-$CI_COMMIT_REF_NAME-win32.zip"
  only:
    - master
    - next
    - tags

latest_tag:
  stage: deploy
  interruptible: true
  cache: {}
  script:
    - echo $CI_COMMIT_REF_NAME >latest
    - lftp -c "set cmd:fail-exit yes; set ftp:ssl-allow no; open -u $USERNAME,$PASSWORD $HOST; cd site/downloads; put latest"
  only:
    - tags

deploy_osx:
  stage: deploy
  interruptible: true
  cache: {}
  dependencies:
    - pkg_osx
  script:
    - mkdir build_mac
    - cd build_mac
    - wget -qO- http://mugen.karaokes.moe/downloads/dist_macos.tar.gz | tar xvz
    - chmod -R +x app/bin
    - mkdir -p app/jingles
    - cd app/jingles
    - wget -qO- https://lab.shelter.moe/karaokemugen/jingles/repository/master/archive.tar | tar xv
    - mv -f jingles-master*/* .
    - rm -Rf jingles-master*
    - rm -f archive.tar
    - cd ../..
    - cp -f ../bin/karaokemugen-app KaraokeMugen
    - cp -f ../config.sample.yml .
    - cp -Rf ../samples .
    - tar cvz * >KaraokeMugen-$CI_COMMIT_REF_NAME-macOS.tar.gz
    - cd ..
    - lftp -c "set cmd:fail-exit yes; set ftp:ssl-allow no; open -u $USERNAME,$PASSWORD $HOST; cd site/downloads; put build_mac/KaraokeMugen-$CI_COMMIT_REF_NAME-macOS.tar.gz"
  only:
    - master
    - next
    - tags

apidoc:
  stage: deploy
  interruptible: true
  cache: {}
  script:
    - npm install -g apidoc
    - apidoc -i src/_controllers -o apidoc -t apidoc_template
    - cd apidoc
    - lftp -c "set ftp:ssl-allow no; open -u $USERNAME,$PASSWORD $HOST; mkdir -p site/apidoc/$CI_COMMIT_REF_NAME; cd site/apidoc/$CI_COMMIT_REF_NAME; mirror -Rnev --parallel=10"
  only:
    - master
    - next
