image: axelterizaki/karaokemugen-ci:node-12

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  ELECTRON_CACHE: .cache/electron

cache:
  key: km-app-${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - systempanel/node_modules/
    - frontend/node_modules/

stages:
  - test
  - build
  - package
  - deploy

test:
  stage: test
  retry:
    max: 2
  interruptible: true
  services:
    - postgres:12.2
  variables:
    POSTGRES_USER: karaokemugen_app
    POSTGRES_PASSWORD: musubi
  artifacts:
    expire_in: 2 hours
    name: km-app-test-${CI_COMMIT_REF_SLUG}
    paths:
    - dist/
  script:
    - yarn install --cache-folder .yarn
    - touch mpv
    - cp -f config.CICD.yml config.yml
    - cp -f database.CICD.json database.json
    - export LANG=en_US
    - node --version
    - node util/extUnaccent.js
    - yarn startNoElectron --debug --test &disown
    - bash test/run.sh
  only:
    - master
    - next
    - tags

build-react:
  stage: build
  dependencies:
    - test
  interruptible: true
  artifacts:
    expire_in: 2 hours
    name: km-app-build-${CI_COMMIT_REF_SLUG}
    paths:
    - systempanel/build/
    - dist/
    - frontend/build/
  script:
    - yarn installSystemPanel
    - yarn installFrontend
    - yarn buildSystemPanel
    - yarn buildFrontend
  only:
    - master
    - next
    - tags

pkg_linux:
  stage: package
  image: electronuserland/builder:latest
  cache:
    key: km-app-${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
      - systempanel/node_modules/
      - frontend/node_modules/
    policy: pull
  interruptible: true
  artifacts:
    expire_in: 2 hours
    name: km-app-pkglinux-${CI_COMMIT_REF_SLUG}
    paths:
      - release
  dependencies:
    - build-react
  script:
    - ./node_modules/.bin/electron-builder -l --publish always
    - ls -la packages/
    - mkdir release
    - mv packages/*.AppImage release/
    - mv packages/*.yml release/
    - cd release
  only:
    - master
    - next
    - tags

pkg_win:
  stage: package
  image: electronuserland/builder:wine-mono
  cache:
    key: km-app-${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
      - systempanel/node_modules/
      - frontend/node_modules/
    policy: pull
  interruptible: true
  artifacts:
    name: km-app-pkgwin-${CI_COMMIT_REF_SLUG}
    paths:
      - release
  dependencies:
    - build-react
  script:
    - apt-get update -qq && apt-get install -y -qq zip
    - wget -qO- http://mugen.karaokes.moe/downloads/dist_win-3.2.tar.gz | tar xz
    - ./node_modules/.bin/electron-builder -w --publish always
    - ls -la packages/
    - mkdir release
    - mv packages/*.exe release/
    - mv packages/*.yml release/
    - mv packages/*.blockmap release/
    - touch portable
    - zip -rv packages/*.zip portable
    - mv packages/*.zip release/
    - cd release
  only:
    - master
    - next
    - tags

pkg_mac:
  stage: package
  cache:
    key: km-app-${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
      - systempanel/node_modules/
      - frontend/node_modules/
    policy: pull
  retry:
    max: 2
  tags:
    - macos
  interruptible: true
  artifacts:
    name: km-app-pkgmac-${CI_COMMIT_REF_SLUG}
    paths:
      - release
  dependencies:
    - build-react
  variables:
    CSC_IDENTITY_AUTO_DISCOVERY: "false"
    ARTIFACT_DOWNLOAD_ATTEMPTS: 10
    RESTORE_CACHE_ATTEMPTS: 10
  script:
    - wget -qO- http://mugen.karaokes.moe/downloads/dist_mac-3.2.tar.gz | tar xvz
    - ./node_modules/.bin/electron-builder -m
    - ls -la packages/
    - mkdir release
    - mv packages/*.dmg release/
    - mv packages/*.blockmap release/
  only:
    - master
    - next
    - tags

deploy_mac:
  stage: deploy
  image: minidocks/lftp
  interruptible: true
  cache: {}
  dependencies:
    - pkg_mac
  needs:
    - pkg_mac
  script:
    - ls -la release/*
    - lftp -c "set cmd:fail-exit yes; set ftp:ssl-allow no; open -u $USERNAME,$PASSWORD $HOST; cd site/downloads; mput release/*"
  only:
    - master
    - next
    - tags

deploy_win:
  stage: deploy
  image: minidocks/lftp
  interruptible: true
  cache: {}
  dependencies:
    - pkg_win
  needs:
    - pkg_win
  script:
    - ls -la release/*
    - lftp -c "set cmd:fail-exit yes; set ftp:ssl-allow no; open -u $USERNAME,$PASSWORD $HOST; cd site/downloads; mput release/*"
  only:
    - master
    - next
    - tags

deploy_linux:
  stage: deploy
  image: minidocks/lftp
  interruptible: true
  cache: {}
  dependencies:
    - pkg_linux
  needs:
    - pkg_linux
  script:
    - ls -la release/*
    - lftp -c "set cmd:fail-exit yes; set ftp:ssl-allow no; open -u $USERNAME,$PASSWORD $HOST; cd site/downloads; mput release/*"
  only:
    - master
    - next
    - tags

apidoc:
  stage: deploy
  interruptible: true
  cache:
    key: km-app-${CI_COMMIT_REF_SLUG}
    policy: pull
  script:
    - ./node_modules/.bin/apidoc -i src/controllers -o apidoc -t apidoc_template
    - cd apidoc
    - lftp -c "set ftp:ssl-allow no; open -u $USERNAME,$PASSWORD $HOST; mkdir -p site/apidoc/$CI_COMMIT_REF_NAME; cd site/apidoc/$CI_COMMIT_REF_NAME; mirror -Rnev --parallel=10"
  only:
    - master
    - next
