image: node:8-stretch

cache:
  key: km
  paths:
  - node_modules/
  - bin/
  - react_client/node_modules/

before_script:
  - apt-get update -qq && apt-get install -y -qq lftp zip
  - rm -f /usr/local/bin/yarn
  - npm install -g pkg@4.2.6 yarn apidoc

stages:
  - test
  - build
  - package
  - deploy

test:
  stage: test
  script:
    - wget -c https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-64bit-static.tar.xz    
    - tar xf ffmpeg-release-64bit-static.tar.xz
    - mv ffmpeg-3* ffmpeg
    - yarn install
    - touch mpv
    - echo "BinffmpegLinux=ffmpeg/ffmpeg" >>config.ini
    - echo "BinPlayerLinux=mpv" >>config.ini
    - mkdir -p /builds/karaokemugen/karaokemugen-app/app/data
    - mkdir -p /builds/karaokemugen/karaokemugen-app/app/db
    - cp -R samples/* /builds/karaokemugen/karaokemugen-app/app/data/
    - export LANG=en_US
    - npm start -- --debug --test &disown
    - bash test/run.sh
  only:
    - next

build:
  stage: build
  artifacts:
    expire_in: 1 day
    paths:
      - dist/
  script:
    - npm run-script build    
    - yarn install --production
    - cd node_modules
    - find -name *.node -delete
  only:
    - master
    - next
    - tags

pkg_win:
  stage: package
  dependencies:
    - build
  artifacts:
    name: "$CI_COMMIT_REF_NAME-win"
    expire_in: 1 day
    paths:
      - bin/
  script:
    - mkdir -p bin
    - pkg . --targets node8-win-x64 --out-path bin 
  only:
    - master
    - next
    - tags

pkg_osx:
  stage: package
  dependencies:
    - build
  artifacts:
    expire_in: 1 day
    paths:
      - bin/
  script:
    - mkdir -p bin
    - pkg . --targets node8-macos-x64 --out-path bin 
  only:
    - master
    - next
    - tags

deploy_win:
  stage: deploy
  dependencies:
    - pkg_win
  script:
    - mkdir build_win
    - cd build_win
    - wget http://mugen.karaokes.moe/downloads/dist_win.tar.gz
    - tar xvzf dist_win.tar.gz
    - rm dist_win.tar.gz
    - cp -f ../bin/karaokemugen-app.exe KaraokeMugen.exe
    - cp -f ../config.ini.sample .
    - zip -r KaraokeMugen-$CI_COMMIT_REF_NAME-win64.zip *
    - lftp -c "set ftp:ssl-allow no; open -u $USERNAME,$PASSWORD $HOST; cd downloads; put KaraokeMugen-$CI_COMMIT_REF_NAME-win64.zip"    
  only:
    - master
    - next
    - tags

latest_tag:
  stage: deploy
  script:
    - echo $CI_COMMIT_REF_NAME >latest
    - lftp -c "set ftp:ssl-allow no; open -u $USERNAME,$PASSWORD $HOST; cd downloads; put latest"
  only: 
    - tags

deploy_osx:
  stage: deploy
  dependencies:
    - pkg_osx
  script:
    - mkdir build_mac
    - cd build_mac
    - wget http://mugen.karaokes.moe/downloads/dist_macos.tar.gz
    - tar xvzf dist_macos.tar.gz
    - rm dist_macos.tar.gz
    - cp -f ../bin/karaokemugen-app KaraokeMugen
    - cp -f ../config.ini.sample .
    - zip -r KaraokeMugen-$CI_COMMIT_REF_NAME-macOS.zip *
    - lftp -c "set ftp:ssl-allow no; open -u $USERNAME,$PASSWORD $HOST; cd downloads; put KaraokeMugen-$CI_COMMIT_REF_NAME-macOS.zip"    
  only:
    - master
    - next
    - tags

apidoc:
  stage: deploy
  script:    
    - apidoc -i src -o apidoc -t apidoc_template
    - cd apidoc
    - lftp -c "set ftp:ssl-allow no; open -u $USERNAME,$PASSWORD $HOST; cd apidoc; mirror -Rnev --parallel=10"
  only:
    - master