image: node:8

cache:
  paths:
  - node_modules/

before_script:
  - npm install

stages: 
  - test
  - deploy

test:
  stage: test
  script: "echo lol"

deploy:
  stage: deploy
  script: "echo lol2"
  only: 
    - master

