image: node:8

cache:
  paths:
  - node_modules/

before_script:
  - npm install
  - mkdir -p app/data
  - mkdir -p app/db
  - cp -R samples/* app/data/

stages: 
  - test
  - deploy

test:
  stage: test
  script: "echo lol"

deploy:
  stage: deploy
  script: "echo lol2"
  only: 
    - master

