image: node:8-stretch

cache:
  key: km
  paths:
  - node_modules/
  - bin/
  - react_client/node_modules/

before_script:
  - rm -f /usr/local/bin/yarn
  - rm -f /usr/local/bin/yarnpkg
  - npm install -g pkg@4.2.6 yarn apidoc

stages:
  - test
  - build
  - package
  - deploy

test:
  stage: test
  script:
    - apt-get update -qq && apt-get install -y -qq ffmpeg
    - yarn install --check-files --force
    - touch mpv
    - echo "BinPlayerLinux=mpv" >>config.ini
    - mkdir -p /builds/karaokemugen/karaokemugen-app/app/data
    - cp -R samples/* /builds/karaokemugen/karaokemugen-app/app/data/
    - export LANG=en_US
    - node --version
    - yarn start --debug --test &disown
    - bash test/run.sh
  only:
    - master
    - next
    - tags

build:
  stage: build
  artifacts:
    expire_in: 1 day
    paths:
      - dist/
  script:
    - npm install -g modclean
    - yarn build
    - yarn install --production
    - cd node_modules
    - find -name *.node -delete
    - modclean -r
  only:
    - master
    - next
    - tags

pkg_win:
  stage: package
  dependencies:
    - build
  artifacts:
    name: "$CI_COMMIT_REF_NAME-win"
    expire_in: 1 day
    paths:
      - bin/
  script:
    - mkdir -p bin
    - pkg . -d --targets node8-win-x64 --out-path bin 
  only:
    - master
    - next
    - tags

pkg_osx:
  stage: package
  dependencies:
    - build
  artifacts:
    expire_in: 1 day
    paths:
      - bin/
  script:
    - mkdir -p bin
    - pkg . -d --targets node8-macos-x64 --out-path bin 
  only:
    - master
    - next
    - tags

deploy_win:
  stage: deploy
  dependencies:
    - pkg_win
  script:
    - apt-get update -qq && apt-get install -y -qq lftp zip  
    - mkdir build_win
    - cd build_win
    - wget http://mugen.karaokes.moe/downloads/dist_win.tar.gz
    - tar xvzf dist_win.tar.gz
    - rm dist_win.tar.gz
    - mkdir -p app/jingles
    - cd app/jingles
    - wget https://lab.shelter.moe/karaokemugen/jingles/repository/master/archive.tar
    - tar xvf archive.tar
    - mv -f jingles-master*/* .
    - rm -Rf jingles-master*    
    - rm -f archive.tar
    - cd ../..
    - cp -f ../bin/karaokemugen-app.exe KaraokeMugen.exe
    - cp -f ../config.ini.sample .
    - cp -Rf ../samples .
    - zip -r KaraokeMugen-$CI_COMMIT_REF_NAME-win64.zip *    
    - cd ..
    - lftp -c "set ftp:ssl-allow no; open -u $USERNAME,$PASSWORD $HOST; cd site/downloads; put build_win/KaraokeMugen-$CI_COMMIT_REF_NAME-win64.zip"   
  only:
    - master
    - next
    - tags

latest_tag:
  stage: deploy
  script:
    - apt-get update -qq && apt-get install -y -qq lftp
    - echo $CI_COMMIT_REF_NAME >latest
    - lftp -c "set ftp:ssl-allow no; open -u $USERNAME,$PASSWORD $HOST; cd site/downloads; put latest"
  only: 
    - tags

deploy_osx:
  stage: deploy
  dependencies:
    - pkg_osx
  script:
    - apt-get update -qq && apt-get install -y -qq lftp zip  
    - mkdir build_mac
    - cd build_mac
    - wget http://mugen.karaokes.moe/downloads/dist_macos.tar.gz
    - tar xvzf dist_macos.tar.gz
    - rm dist_macos.tar.gz
    - mkdir -p app/jingles
    - cd app/jingles
    - wget https://lab.shelter.moe/karaokemugen/jingles/repository/master/archive.tar
    - tar xvf archive.tar
    - mv -f jingles-master*/* .
    - rm -Rf jingles-master*    
    - rm -f archive.tar
    - cd ../..
    - cp -f ../bin/karaokemugen-app KaraokeMugen
    - cp -f ../config.ini.sample .
    - cp -Rf ../samples .
    - zip -r KaraokeMugen-$CI_COMMIT_REF_NAME-macOS.zip *
    - cd ..
    - lftp -c "set ftp:ssl-allow no; open -u $USERNAME,$PASSWORD $HOST; cd site/downloads; put build_mac/KaraokeMugen-$CI_COMMIT_REF_NAME-macOS.zip"    
  only:
    - master
    - next
    - tags

apidoc:
  stage: deploy
  script:    
    - apt-get update -qq && apt-get install -y -qq lftp  
    - apidoc -i src/_controllers -o apidoc -t apidoc_template
    - cd apidoc
    - lftp -c "set ftp:ssl-allow no; open -u $USERNAME,$PASSWORD $HOST; cd site/apidoc; mirror -Rnev --parallel=10"
  only:
    - master
    - tags
