image: axelterizaki/karaokemugen-ci:node-10

cache:
  key: km
  paths:
  - node_modules/
  - bin/
  - react_systempanel/node_modules/

stages:
  - test
  - build
  - package
  - deploy

test:
  stage: test
  services:
    - postgres:10.6
  variables:
    POSTGRES_USER: karaokemugen_app
    POSTGRES_PASSWORD: musubi
  script:
    - yarn install --check-files --force
    - touch mpv
    - echo "BinPlayerLinux=mpv" >>config.ini
    - mkdir -p /builds/karaokemugen/karaokemugen-app/app/data
    - cp -R samples/* /builds/karaokemugen/karaokemugen-app/app/data/
    - cp -f database.CICD.json database.json
    - export LANG=en_US
    - node --version
    - node util/extUnaccent.js
    - yarn start --debug --test &disown
    - bash test/run.sh
  only:
    - master
    - next
    - tags

build:
  stage: build
  artifacts:
    expire_in: 1 day
    paths:
      - dist/
      - react_client/build/
  script:
    - npm install -g modclean
    - yarn build
    - yarn install --production
    - cd node_modules
    - find -name *.node -delete
    - modclean -r
  only:
    - master
    - next
    - tags

pkg_win:
  stage: package
  dependencies:
    - build
  artifacts:
    name: "$CI_COMMIT_REF_NAME-win"
    expire_in: 1 day
    paths:
      - bin/
  script:
    - mkdir -p bin
    - npm install -g pkg
    - pkg . -d --targets node10-win-x64 --out-path bin
  only:
    - master
    - next
    - tags

pkg_osx:
  stage: package
  dependencies:
    - build
  artifacts:
    expire_in: 1 day
    paths:
      - bin/
  script:
    - mkdir -p bin
    - npm install -g pkg
    - pkg . -d --targets node10-macos-x64 --out-path bin
  only:
    - master
    - next
    - tags

deploy_win:
  stage: deploy
  dependencies:
    - pkg_win
  script:
    - mkdir build_win
    - cd build_win
    - wget -qO- http://mugen.karaokes.moe/downloads/dist_win_node10.tar.gz | tar xvz
    - mkdir -p app/jingles
    - cd app/jingles
    - wget -qO- https://lab.shelter.moe/karaokemugen/jingles/repository/master/archive.tar | tar xv
    - mv -f jingles-master*/* .
    - rm -Rf jingles-master*
    - cd ../..
    - cp -f ../bin/karaokemugen-app.exe KaraokeMugen.exe
    - cp -f ../config.sample.ini .
    - cp -Rf ../samples .
    - zip -r KaraokeMugen-$CI_COMMIT_REF_NAME-win64.zip *
    - cd ..
    - lftp -c "set ftp:ssl-allow no; open -u $USERNAME,$PASSWORD $HOST; cd site/downloads; put build_win/KaraokeMugen-$CI_COMMIT_REF_NAME-win64.zip"
  only:
    - master
    - next
    - tags

latest_tag:
  stage: deploy
  script:
    - echo $CI_COMMIT_REF_NAME >latest
    - lftp -c "set ftp:ssl-allow no; open -u $USERNAME,$PASSWORD $HOST; cd site/downloads; put latest"
  only:
    - tags

deploy_osx:
  stage: deploy
  dependencies:
    - pkg_osx
  script:
    - mkdir build_mac
    - cd build_mac
    - wget -qO- http://mugen.karaokes.moe/downloads/dist_macos.tar.gz | tar xvz
    - chmod -R +x app/bin
    - mkdir -p app/jingles
    - cd app/jingles
    - wget -qO- https://lab.shelter.moe/karaokemugen/jingles/repository/master/archive.tar | tar xv
    - mv -f jingles-master*/* .
    - rm -Rf jingles-master*
    - rm -f archive.tar
    - cd ../..
    - cp -f ../bin/karaokemugen-app KaraokeMugen
    - cp -f ../config.sample.ini .
    - cp -Rf ../samples .
    - tar cvz * >KaraokeMugen-$CI_COMMIT_REF_NAME-macOS.tar.gz
    - cd ..
    - lftp -c "set ftp:ssl-allow no; open -u $USERNAME,$PASSWORD $HOST; cd site/downloads; put build_mac/KaraokeMugen-$CI_COMMIT_REF_NAME-macOS.tar.gz"
  only:
    - master
    - next
    - tags

apidoc:
  stage: deploy
  script:
    - npm install -g apidoc
    - apidoc -i src/_controllers -o apidoc -t apidoc_template
    - cd apidoc
    - lftp -c "set ftp:ssl-allow no; open -u $USERNAME,$PASSWORD $HOST; mkdir -p site/apidoc/$CI_COMMIT_REF_NAME; cd site/apidoc/$CI_COMMIT_REF_NAME; mirror -Rnev --parallel=10"
  only:
    - master
    - next
