image: node:8-stretch

cache:
  paths:
  - node_modules/

before_script:
  - npm install
  - npm install -g apidoc
  - mkdir -p /builds/karaokemugen/karaokemugen-app/app/data
  - mkdir -p /builds/karaokemugen/karaokemugen-app/app/db
  - cp -R samples/* /builds/karaokemugen/karaokemugen-app/app/data/
  - export LANG=en_US

stages:
  - test
  - deploy
  - deploy_apidoc

test:
  stage: test
  script:
    - node src/index.js --debug --test &disown
    - bash test/run.sh
  only:
    - test_removed

deploy:
  stage: deploy
  script: "echo lol2"
  only:
    - master

deploy_apidoc:
  stage: deploy_apidoc
  script:
    - apt-get update -qq && apt-get install -y -qq lftp
    - npm install -g apidoc
    - apidoc -i src -o apidoc
    - cd apidoc
    - lftp -c "set ftp:ssl-allow no; open -u $USERNAME,$PASSWORD $HOST; cd apidoc; mirror -Rnev --parallel=10"
  only:
    - master