image: node:8-stretch

cache:
  paths:
  - node_modules/

before_script:
  - npm install
  - mkdir -p /builds/karaokemugen/karaokemugen-app/app/data
  - mkdir -p /builds/karaokemugen/karaokemugen-app/app/db
  - cp -R samples/* /builds/karaokemugen/karaokemugen-app/app/data/
  - export LANG=en_US

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - node src/index.js --debug --test &disown
    - bash test/run.sh
  only:
    - test

deploy:
  stage: deploy
  script: "echo lol2"
  only:
    - master

