image: axelterizaki/karaokemugen-ci:node-12

variables:
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  key: km-app-${CI_COMMIT_REF_SLUG}
  paths:
    - dist
    - node_modules/
    - systempanel/node_modules/
    - frontend/node_modules/
    - ~/.cache/electron
    - ~/.cache/electron-builder

stages:
  - test
  - build
  - package
  - deploy

test:
  stage: test
  retry:
    max: 2
  interruptible: true
  services:
    - postgres:10.6
  variables:
    POSTGRES_USER: karaokemugen_app
    POSTGRES_PASSWORD: musubi
  script:
    - yarn install --check-files --force
    - yarn installSystemPanel --check-files --force
    - yarn installFrontend --check-files --force
    - touch mpv
    - cp -f config.CICD.yml config.yml
    - cp -f database.CICD.json database.json
    - export LANG=en_US
    - node --version
    - node util/extUnaccent.js
    - yarn startNoElectron --debug --test &disown
    - bash test/run.sh
  only:
    - master
    - next
    - tags
    - 533-investigate-use-of-electron

build:
  stage: build
  interruptible: true
  artifacts:
    expire_in: 1 days
    name: km-app-build-${CI_COMMIT_REF_SLUG}
    paths:
    - systempanel/build/
    - dist/
    - frontend/build/
  script:
    - npm install -g parcel-bundler
    - yarn build
    - yarn buildSystemPanel
    - yarn buildFrontend
  only:
    - master
    - next
    - tags
    - 533-investigate-use-of-electron

pkg_win:
  stage: package
  image: electronuserland/builder:wine
  interruptible: true
  artifacts:
    expire_in: 1 day
    name: km-app-pkgwin-${CI_COMMIT_REF_SLUG}
    paths:
      - out
  dependencies:
    - build
  script:
    - apt-get update -qq && apt-get install -y -qq zip
    - wget -qO- http://mugen.karaokes.moe/downloads/dist_win-3.2.tar.gz | tar xvz
    - ./node_modules/.bin/electron-builder -w
    - ls -la packages/
    - mkdir out
    - mv packages/*.exe out/
    - cp -f config.sample.yml out/
    - cd out
    - touch portable
    - zip -r KaraokeMugen-$CI_COMMIT_REF_NAME-win64.zip *
  only:
    - master
    - next
    - tags
    - 533-investigate-use-of-electron

deploy_win:
  stage: deploy
  interruptible: true
  dependencies:
    - pkg_win
  script:
    - lftp -c "set cmd:fail-exit yes; set ftp:ssl-allow no; open -u $USERNAME,$PASSWORD $HOST; cd site/downloads; put out/KaraokeMugen-$CI_COMMIT_REF_NAME-win64.zip"
  only:
    - master
    - next
    - tags

latest_tag:
  stage: deploy
  interruptible: true
  script:
    - echo $CI_COMMIT_REF_NAME >latest
    - lftp -c "set cmd:fail-exit yes; set ftp:ssl-allow no; open -u $USERNAME,$PASSWORD $HOST; cd site/downloads; put latest"
  only:
    - tags
