---
App:
  # FirstRun is set to false after user completed the tutorial. Reset it to true to generate a new admin password
  FirstRun: true
  # JWT secret used to salt passwords (uuid)
  JwtSecret: Change me
  # Application quick start (like --noBaseCheck)
  QuickStart: false
  # Instace ID
  InstanceID: uuid here
Online:
  # Host for your KM Server
  Host: kara.moe
  # Should your instance sends stats? True/false. Undefined means the app will ask the user a question if it wants to send stats to KM Server.
  Stats: undefined
  # Should your instance sends error logs to sentry.io? True/false. Undefined means the app will ask the user a question if it wants to send errors.
  ErrorTracking: undefined
  # Should we use KM Server's URL shortener? Turns connection URL into http://kara.moe for example
  URL: true
  # Should we allow users to register/login accounts on kara.moe ?
  Users: true
  Updates:
    App: true
    Medias:
      Intros: true
      Jingles: true
      Outros: true
      Encores: true
      Sponsors: true
  # Use Discord's rich presence to display your activity on your profile
  Discord:
    DisplayActivity: true
Frontend:
  # Minutes before users are considered signed out
  AuthExpireTime: 15
  # Webapp mode :
  # 0 : closed
  # 1 : Current playlist/song only (restricted)
  # 2 : Opened (all features available)
  Mode: 2
  # Port to listen to
  Port: 1337
  Permissions:
    # Permissions for users
    AllowNicknameChange: true
    AllowViewBlacklist: true
    AllowViewBlacklistCriterias: true
    AllowViewWhitelist: true
  # How to display series names
  # 0 : Original name (generally romanji)
  # 1 : Use song language (fallbacks to english then original)
  # 2 : Use KM's language (fallbacks to english then original)
  # 3 : Use user language (fallbacks to english then original)
  SeriesLanguageMode: 3
  ShowAvatarsOnPlaylist: true

Gitlab:
  # Enable or not gitlab posting
  Enable: false
  # URL to your gitlab instance
  Host: https://lab.shelter.moe
  # Access token
  Token: xxx
  # Project ID where you want issues posted
  ProjectID: 1234
  Template:
    Suggestion:
      Description: >
        # Karaoke suggestion


        **Title** : $title


        **Serie** : $serie


        **Type** : $type


        **Link** : $link
      Title: "[Suggestion] $serie - $title"
      Labels:
        - suggestion
Karaoke:
  # Autostart playing songs if no song is playing and a song is added
  Autoplay: false
  # Classic (Karaoke box) mode
  ClassicMode: false
  # Streamer mode options. PauseDuration is in seconds
  StreamerMode:
    Enabled: false
    PauseDuration: 15
    Twitch:
      Enabled: false
      OAuth: 'abcdefgh'
      Channel: 'AxelTerizaki'
  # Repeat playlist once reaching the end
  Repeat: false
  # In private mode try to insert songs in a smart way.
  SmartInsert: false
  Display:
    # Show nickname of the person who requested a song
    Nickname: true
    ConnectionInfo:
      # Enable display of connection messages
      Enabled: true
      # Additional message prepended to the connection URL
      Message: null
      # Override host/IP address
      Host: null
  Poll:
    # Number of choices in poll
    Choices: 4
    # Enable/disable song polls
    Enabled: false
    # Time before poll closes after beginning in seconds
    Timeout: 30
  Quota:
    # Minutes before a song is automatically freed
    FreeAutoTime: 60
    # Can songs be freed by users?
    FreeUpVote: true
    # How many votes are required at minimum to free a song
    FreeUpVoteRequiredMin: 3
    # How many percent of the connected users are required to free a song
    FreeUpVoteRequiredPercent: 33
    # Number of songs per user
    Songs: 10000
    # Time allowed per user in seconds
    Time: 10000
    # Type of quota:
    # 0 : No quota
    # 1 : Song number quota
    # 2 : Time allowance quota
    Type: 0
Player:
  # Override mpv's video output driver
  mpvVideoOutput: null
  # Background file to load
  Background: null
  # Fullscreen ?
  FullScreen: false
  # Spawn a second monitor window in PIP mode to check what the player is displaying
  Monitor: false
  # No progress bar
  NoBar: true
  # No HUD
  NoHud: true
  # Which screen to display on (0 is first)
  Screen: 0
  # Stay on top
  StayOnTop: true
  PIP:
    # Picture In Picture, like a windowed mode
    Enabled: true
    # Position for the window on screen
    PositionX: Right
    PositionY: Bottom
    # Size in %
    Size: 30
  # Play progress bar in Dock / Taskbar
  ProgressBarDock: true
  # When playing mp3s, enable/disable visualization effects.
  VisualizationEffects: false
  # Volume
  Volume: 100
  # Hardware decoding. See mpv manual for more info
  HardwareDecoding: auto-safe
  # Extra mpv commandline arguments example
  ExtraCommandLine: --tone-mapping=reinhard
Playlist:
  # What to do at the end of playlist :
  # - random : plays random songs, should usually be used with autoplay
  # - repeat : cycles through the playlist
  # - none : just end karaoke
  EndOfPlaylistAction: none
  # Should a message be displayed on screen inviting people to add songs?
  RandomSongsAfterEndMessage: true
  # Allow duplicates in current playlist
  AllowDuplicates: false
  # Allow duplicate series or singers in current playlist
  AllowDuplicateSeries: true
  # Time after which a song is not considered recently played anymore in minutes
  MaxDejaVuTime: 60
  # Enable/Disable Intro Videos
  IntroVideos: true
  # Specify an intro video file. KM will search in all Intro folders for that file and will play it instead of selecting a random one.
  Medias:
    Jingles:
      Enabled: true
      Interval: 20
    Sponsors:
      Enabled: true
      Interval: 50
    Intros:
      Enabled: true
      File: PS1-Nanami.mp4
      Message: "Let's Karaoke!"
    Outros:
      Enabled: false
      File: Byebye.mp4
      Message: "That's all folks!"
    Encores:
      Enabled: false
      File: encoru.mp4
      Message: "This is the last song!"
  MysterySongs:
    # Invisible songs are not hidden (they appear as a slot in playlist)
    Hide: false
    # Should songs added by admin be invisible?
    AddedSongVisibilityAdmin: false
    # Should songs added by public be invisible?
    AddedSongVisibilityPublic: false
    # List of mystery songs labels
    Labels:
    - ???
    - Chanson mystère !
System:
  Binaries:
    Player:
      Linux: /usr/bin/mpv
      OSX: app/bin/mpv.app/Contents/MacOS/mpv
      Windows: app/bin/mpv.exe
    ffmpeg:
      Linux: /usr/bin/ffmpeg
      OSX: app/bin/ffmpeg
      Windows: app/bin/ffmpeg.exe
    Postgres:
      Windows: app/bin/postgres/bin/
      OSX: app/bin/postgres/bin/
      Linux: app/bin/postgres/bin/
  Repositories:
    - Name: kara.moe
      Online: true
      Path:
        Karas:
          - repos/kara.moe/karaokes
        Lyrics:
          - repos/kara.moe/lyrics
        Medias:
          - repos/kara.moe/medias
        Series:
          - repos/kara.moe/series
        Tags:
          - repos/kara.moe/tags
    - Name: world.karaokes.moe
      Online: true
      Enabled: false
      Path:
        Karas:
          - repos/world/karaokes
        Lyrics:
          - repos/world/lyrics
        Medias:
          - repos/world/medias
        Series:
          - repos/world/series
        Tags:
          - repos/world/tags
    - Name: Local
      Online: false
      Path:
        Karas:
          - repos/Local/karaokes
        Lyrics:
          - repos/Local/lyrics
        Medias:
          - repos/Local/medias
        Series:
          - repos/Local/series
        Tags:
          - repos/Local/tags
  Path:
    # Some paths like Background, karas lyrics medias, etc. can have multiple entries.
    Avatars: avatars
    Backgrounds:
      - backgrounds
    Bin: bin
    Import: import
    Jingles:
      - jingles
      - jingles/KaraokeMugen
    Intros:
      - intros
      - intros/KaraokeMugen
    Outros:
      - outros
    Encores:
      - encores
    Temp: temp
    DB: db
