---
App:
  # FirstRun is set to false after user completed the tutorial. Reset it to true to generate a new admin password
  FirstRun: true
  # Instance ID (uuid)
  InstanceID: Change me
  # JWT secret used to salt passwords (uuid)
  JwtSecret: Change me
  # Mail to send song suggestions to when a user can't find the song he wants in the app. Defaults to a mail which automatically creates issues on KM's base repository
  karaSuggestionMail: shelter.lab+karaokemugen/karaokebase+9cvqz5cb128c57iluad54wdqg@mahoro-net.org

Online:
  # Host for your KM Server
  Host: kara.moe
  # Should your instance sends stats? True/false. Undefined means the app will ask the user a question if it wants to send stats to KM Server
  Stats: undefined
  # Should we use KM Server's URL shortener? Turns connection URL into http://kara.moe for example
  URL: true
  # Should we allow users to register/login accounts on kara.moe ?
  Users: true

Frontend:
  # Minutes before users are considered signed out
  AuthExpireTime: 15
  # Webapp mode :
  # 0 : closed
  # 1 : Current playlist/song only (restricted)
  # 2 : Opened (all features available)
  Mode: 2
  # Port to listen to
  Port: 1337
  Permissions:
    # Permissions for users
    AllowNicknameChange: true
    AllowViewBlacklist: true
    AllowViewBlacklistCriterias: true
    AllowViewWhitelist: true
  # How to display series names
  # 0 : Original name (generally romanji)
  # 1 : Use song language (fallbacks to english then original)
  # 2 : Use KM's language (fallbacks to english then original)
  # 3 : Use user language (fallbacks to english then original)
  SeriesLanguageMode: 3

Gitlab:
  # Enable or not gitlab posting
  Enable: false
  # URL to your gitlab instance
  Host: https://lab.shelter.moe
  # Access token
  Token: xxx
  # Project ID where you want issues posted
  ProjectID: 1234
  Template:
    Suggestion:
      Description: Hello, please add this! Thank you, $username
      Title: New kara suggestion - $kara
      Labels:
        - suggestion
Karaoke:
  # Autostart playing songs if no song is playing and a song is added
  Autoplay: false
  # Generate video previews for the web interface
  CreatePreviews: false
  # Number of songs between jingles
  JinglesInterval: 20
  # Private karaoke mode or public karaoke mode.
  Private: true
  # Repeat playlist once reaching the end
  Repeat: false
  # In private mode try to insert songs in a smart way.
  SmartInsert: false
  Display:
    # Show nickname of the person who requested a song
    Nickname: true
    ConnectionInfo:
      # Enable display of connection messages
      Enabled: true
      # Enable QR Code
      QRCode: true
      # Additional message prepended to the connection URL
      Message: null
      # Override host/IP address
      Host: null
  Poll:
    # Number of choices in poll
    Choices: 4
    # Enable/disable song polls
    Enabled: false
    # Time before poll closes after beginning in seconds
    Timeout: 30
  Quota:
    # Minutes before a song is automatically freed
    FreeAutoTime: 60
    # Can songs be freed by users?
    FreeUpVote: true
    # How many votes are required at minimum to free a song
    FreeUpVoteRequiredMin: 3
    # How many percent of the connected users are required to free a song
    FreeUpVoteRequiredPercent: 33
    # Number of songs per user
    Songs: 10000
    # Time allowed per user in seconds
    Time: 10000
    # Type of quota:
    # 0 : No quota
    # 1 : Song number quota
    # 2 : Time allowance quota
    Type: 0
Player:
  # Override mpv's video output driver
  mpvVideoOutput: null
  # Background file to load
  Background: null
  # Fullscreen ?
  FullScreen: false
  # Spawn a second monitor window in PIP mode to check what the player is displaying
  Monitor: false
  # No progress bar
  NoBar: true
  # No HUD
  NoHud: true
  # Which screen to display on (0 is first)
  Screen: 0
  # Stay on top
  StayOnTop: true
  PIP:
    # Picture In Picture, like a windowed mode
    Enabled: true
    # Position for the window on screen
    PositionX: Right
    PositionY: Bottom
    # Size in %
    Size: 30
  # When playing mp3s, enable/disable visualization effects.
  VisualizationEffects: true
Playlist:
  # Allow duplicates in current playlist
  AllowDuplicates: false
  # Time after which a song is not considered recently played anymore in minutes
  MaxDejaVuTime: 60
  # Remove songs from public playlist when they're played.
  RemovePublicOnPlay: false
System:
  Binaries:
    Player:
      Linux: /usr/bin/mpv
      OSX: app/bin/mpv.app/Contents/MacOS/mpv
      Windows: app/bin/mpv.exe
    ffmpeg:
      Linux: /usr/bin/ffmpeg
      OSX: app/bin/ffmpeg
      Windows: app/bin/ffmpeg.exe
    Postgres:
      Windows: app/bin/postgres/bin/
      OSX: app/bin/postgres/bin/
      Linux: app/bin/postgres/bin/
  Path:
    # Some paths like Background, karas lyrics medias, etc. can have multiple entries.
    Avatars: app/avatars
    Backgrounds:
      - app/backgrounds
    Bin: app/bin
    Import: app/import
    Jingles:
      - app/jingles
    Karas:
      - app/data/karas
    Lyrics:
      - app/data/lyrics
    Medias:
      - app/data/medias
    # If set and if a video is not found locally, KM will attempt to load the video from this HTTP server.
    MediasHTTP: null
    Previews: app/previews
    Series:
      - app/data/series
    Temp: app/temp
    DB: app/db
